title: "Data Scientist"
description: >
  I am a passionate and dedicated data scientist with a strong foundation in statistical analysis, machine learning, and data visualization. Recently graduated with a Bachelor's degree in IT from SR Gudlavalleru Engineering College, JNTUK, I am eager to apply my skills to solve real-world problems and contribute to data-driven decision-making.
theme: minima



